#+TITLE:       C贸mo preparo mi entorno con Emacs
#+AUTHOR:      lvaro Gonz谩lez Sotillo
#+EMAIL:       alvarogonzalezsotillo@gmail.com
#+DATE:        2017-10-01 dom
#+URI:         /blog/como-preparo-mi-entorno-con-emacs
#+KEYWORDS:    Emacs, magit, git, latex, reveal
#+TAGS:        emacs, latex
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:t toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Cada vez que llego a un nuevo ordenador tengo que preparar mi entorno, y se puede hacer f谩cilmente con un par de /scripts/


Como profesor, mi trabajo con el ordenador se centra en *Emacs* y *git* para:
- Elaborar transparencias con *Emacs* y *[[https://github.com/yjwen/org-reveal][org-reveal]]*
- Elaborar ejercicios y ex谩menes con *[[https://www.gnu.org/software/auctex/][auctex]]* y *[[https://www.latex-project.org/][latex]]*
- Publicar los materiales con *[[https://pages.github.com/][github pages]]*

Trabajar con mi port谩til es simple, porque el entorno ya est谩 instalado y configurado. Pero cada vez que llego a un PC nuevo (en el aula, en un nuevo departamento,...) necesito reinstalar todo de nuevo.

Para ello tengo preparados un par de /scripts/ para facilitar el proceso. En unos pocos minutos, dependiendo de la conexi贸n de red, el entorno est谩 listo .

#+TOC: headlines 2 local

* Ubuntu
1. Instalaci贸n de *Emacs* 25 y *git*
  #+begin_src sh
  sudo add-apt-repository ppa:kelleyk/emacs
  sudo apt-get update
  sudo apt-get install emacs25 git
  #+end_src
2. Instalaci贸n de *Latex*
  #+begin_src sh 
  sudo apt-get install texlive-collection-binextra \
  texlive-latex-recommended \
  texlive-extra-utils \
  texlive-collection-langspanish \
  texlive-collection-latex \
  texlive-collection-latexextra \
  #+end_src
3. Mi configuraci贸n de *Emacs*:
  #+begin_src sh
  cd $HOME
  git clone https://github.com/alvarogonzalezsotillo/.emacs.d.git
  #+end_src
4. Para instalar los paquetes de *Emacs* necesarios, ejecuto dentro de *Emacs* este c贸digo *elisp*
   #+begin_src lisp
 ;; REINSTALAR LOS PAQUETES (SI ES UN EMACS NUEVO)
 (defun reinstalar-paquetes-en-emacs-nuevo() 
 
   (interactive) 
   ;; LISTA DE PAQUETES INSTALADOS (C-h v package-selected-packages)
   (setq package-selected-packages '(company-restclient ob-restclient restclient-helm restclient transmission hl-line+ treemacs paradox gift-mode org-webpage plsql org-page company-web company-shell company-quickhelp company-emoji company-c-headers company company-auctex helm-company highlight-indent-guides which-key dumb-jump dired-narrow org markdown-mode magit popup-complete scad-preview scad-mode org-attach-screenshot bm yafolding web-mode transpose-frame tablist switch-window swiper sr-speedbar smartparens scala-outline-popup request-deferred rectangle-utils rainbow-delimiters php-mode page-break-lines ox-reveal org-present neotree multiple-cursors image+ htmlize helm-projectile github-browse-file git-timemachine git-link flycheck find-file-in-project expand-region epresent ensime discover diffview crappy-jsp-mode chess calfw browse-at-remote auto-highlight-symbol alert adaptive-wrap))
   
   (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
 
   (package-refresh-contents)
   (package-initialize)  
 
   (package-install-selected-packages))
 
 (require 'package)
 (reinstalar-paquetes-en-emacs-nuevo)
   #+end_src
 
* *Windows* con *Cygwin*
Si necesito instalar mi sistema en *Windows* utilizo *Cygwin*, para evitar problemas de integraci贸n de paquetes (por ejemplo, *[[https://github.com/magit/magit][magit]]* no funciona correctamente). Eso s铆, el rendimiento es bastante peor que con herramientas de *Windows* nativas. El procedimiento es el siguiente:
1. Descargar el fichero [[https://www.cygwin.com/setup-x86_64.exe]]
2. Realizar una instalaci贸n b谩sica, a帽adiendo el paquete =wget=
3. Instalar =apt-cyg=
  #+begin_src bash  
  wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg
  install apt-cyg /bin
  #+end_src
4. Instalar *git*
  #+begin_src bash
  apt-cyg install git
  
  # Soluci贸n al problema de petici贸n de contrase帽a con magit (requiere XOrg)
  apt-cyg install git git-gui xorg
  git config --global core.askpass /usr/libexec/git-core/git-gui--askpass
  #+end_src
5. Instalar *Emacs*
  #+begin_src bash 
  apt-cyg install emacs-w32
  #+end_src
6. Instalar *Latex*
  #+begin_src bash
  apt-cyg install texlive \ 
  texlive-collection-basic \ 
  texlive-collection-binextra \ 
  texlive-collection-fontsextra \ 
  texlive-collection-fontsrecommended \ 
  texlive-collection-fontutils \ 
  texlive-collection-formatsextra \ 
  texlive-collection-genericextra \ 
  texlive-collection-genericrecommended \ 
  texlive-collection-langenglish \ 
  texlive-collection-langeuropean \ 
  texlive-collection-langspanish \ 
  texlive-collection-latex \ 
  texlive-collection-latexextra \ 
  texlive-collection-latexrecommended \ 
  texlive-collection-pictures \ 
  texlive-collection-plainextra \ 
  texlive-collection-pstricks
  
  texconfig rehash
  mktexlsr
  #+end_src
7. Los pasos para configurar *emacs* son equivalentes a los de la instalaci贸n en *ubuntu*

