# -*- coding: utf-8-unix; -*-
#+title:       nuevo htpc en casa
#+author:      치lvaro gonz치lez sotillo
#+email:       alvarogonzalezsotillo@gmail.com
#+date:        2018-05-17
#+uri:         /blog/ordenador-de-sobremesa-servidor-htpc

#+tags: 
#+description: acabo de comprarme un asus vc-66. mi intenci칩n es utilizarlo como servidor accesible desde internet, pero tambi칠n como htpc. estos son los pasos que he seguido para configurarlo.


#+language:    es
#+options: toc:2

#+attr_html: :align right :style width:10%;max-width:200px;min-width:100px;margin:2em;
[[https://www.asus.com/us/mini-pcs/vivomini-vc66/][file:./asus-vc66.png]]

acabo de comprarme un [[https://www.asus.com/us/mini-pcs/vivomini-vc66/][asus vc-66]]. mi intenci칩n es utilizarlo como servidor accesible desde internet, pero tambi칠n como [[https://es.wikipedia.org/wiki/htpc][htpc]]. estos son los pasos que he seguido para configurarlo.
#+html: <p style="clear:both"></p>

* instalaci칩n del sistema operativo
el ordenador ven칤a con windows 10 preinstalado. aunque el /[[https://es.wikipedia.org/wiki/remote_desktop_protocol][remote desktop]]/ es una buena forma de conectarte a un ordenador de tu lan, no es tan adecuado para un acceso remoto con bajo ancho de banda. en esos casos, una conexi칩n [[https://es.wikipedia.org/wiki/secure_shell][ssh]]/[[https://es.wikipedia.org/wiki/ssh_file_transfer_protocol][sftp]] con la posibilidad de redirigir puertos a [[https://es.wikipedia.org/wiki/vnc][vnc]] me parece m치s adecuada.

de todas formas, windows sigue instalado, que tampoco es cuesti칩n de despreciar una licencia.

** haciendo sitio en el disco

1. particiones del disco duro original
   |---+-----+------+---------+--------------|
   | / | <>  | <>   | <>      | <>           |
   |   | efi | boot | windows | recuperaci칩n |
   |---+-----+------+---------+--------------|
2. tras reducir partici칩n windows
   |---+-----+------+---------+-------+--------------|
   | / | <>  | <>   | <>      | <>    | <>           |
   |   | efi | boot | windows | libre | recuperaci칩n |
   |---+-----+------+---------+-------+--------------|
3. tran instalar ubuntu
   |---+-----+------+---------+-------+--------+------+--------------|
   | / | <>  | <>   | <>      | <>    | <>     | <>   | <>           |
   |   | efi | boot | windows | libre | ubuntu | swap | recuperaci칩n |
   |---+-----+------+---------+-------+--------+------+--------------|
4. crear partici칩n datos compartidos con windows (formato ntfs)
   |---+-----+------+---------+--------------------------+--------+------+--------------|
   | / | <>  | <>   | <>      | <>                       | <>     | <>   | <>           |
   |   | efi | boot | windows | datos compartidos (ntfs) | ubuntu | swap | recuperaci칩n |
   |---+-----+------+---------+--------------------------+--------+------+--------------|

** usuarios
he creado un usuario por defecto para la familia con el [[https://help.ubuntu.com/community/autologin][autologin]] activado.

para compartir ficheros entre los usuarios se utiliza el grupo =discos=, al que pertenecen todos los usuarios
#+begin_src bash
sudo addgroup discos
sudo usermod -a -g discos usuario1
sudo usermod -a -g discos usuario2
#+end_src

las particiones de datos adicionales (como los datos compartidos con windows) se montan con este grupo    
#+begin_example
# /etc/fstab: static file system information.
#
# use 'blkid' to print the universally unique identifier for a
# device; this may be used with uuid= as a more robust way to name devices
# that works even if disks are added and removed. see fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda7 during installation
uuid=04c0c550-c5c3-4ab5-b0f2-02d071836091 /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda1 during installation
uuid=0e07-e3eb  /boot/efi       vfat    umask=0077      0       1
# swap was on /dev/sda8 during installation
uuid=7fa25a22-5511-47c7-9ae8-34d96d23d41d none            swap    sw              0       0

# ntfs compartido con windows
uuid=9e1cf2601cf2333f /datos/datos-compartidos-200m ntfs gid=discos,dmask=002,fmask=113 0 2
#+end_example

* home theater personal computer

#+attr_html: :align right :style width:15%;max-width:200px;min-width:100px;margin:1em;
[[https://www.logitech.com/es-es/product/k400-wireless-keyboard-touchpad][file:./wireless-touch-keyboard-k400-plus.png]]

en la parte /hardware/, basta con conectar el ordenador al televisor por el puerto hdmi y utilizar un teclado inal치mbrico. yo utilizo un [[https://www.logitech.com/es-es/product/k400-wireless-keyboard-touchpad][logitech k400]] que va muy bien, sobre todo por el f치cil acceso a las teclas de volumen (que al final, durante una pel칤cula, es lo que m치s se usa). 

en la parte /software/ he optado por [[https://kodi.tv/][kodi]] con el [[https://kodi.wiki/view/add-on:youtube][plugin de youtube]], aunque al final resulta m치s c칩modo utilizar directamente la web con firefox.

para /esos/ otros contenidos, utilizo [[https://transmissionbt.com/][transmission daemon]]. he seguido los siguientes pasos:
- instalar con =apt install transmission-daemon=
- crear directorio transmission en el disco compartido
- configuraci칩n de transmission (fichero =settings.json=)
     - cambiar usuario y contrase침a de acceso remoto
     - cambiar el directorio por defecto al creado anteriormente
     - escuchar en la direcci칩n =0.0.0.0=, para permitir conexiones desde fuera del equipo, y eliminar la =whitelist= de equipos con la conexi칩n permitida.
     - para que el resto de usuarios puedan leer los ficheros bajados por transmission, hay que a침adirlos al grupo =debian-transmission=
       #+begin_src bash
       sudo usermod -a -g debian-transmission usuario1
       sudo usermod -a -g debian-transmission usuario2
       #+end_src

tras instalar transmission, he a침adido el directorio de bajada a los directorios de video de kodi.

* acceso remoto
el acceso remoto no es solamente acceder al ordenador desde la lan, sino desde cualquier parte de internet. los pasos a seguir son los siguientes:

1. instalar [[https://www.openssh.com/][openssh server]], que nos permitir치 acceder a un terminal y a los ficheros del servidor
   #+begin_src bash
   sudo apt install openssh-server
   #+end_src
2. redirigir un puerto para acceder a ssh desde internet. para ello
   1. configurar el ordenador para tener una ip fija
   2. en el router adsl/fibra, abrir un puerto que se redirija a esa ip fija, al puerto 22 del servidor ssh.

** /always-on/ vs /wake-on-lan/
idealmente, el servidor deber칤a estar siempre encendido. en la pr치ctica no siempre es deseable, aunque solo sea por el gasto continuo de 18w.

para conseguir lo mejor de ambas opciones, puede dejarse al ordenador suspendido (1w) y despertarlo con [[https://es.wikipedia.org/wiki/wake_on_lan][wake-on-lan]] con alguna [[https://play.google.com/store/apps/details?id=com.cbsb.wakelan][aplicaci칩n desde el m칩vil]]. este sistema consiste en enviar un [[https://es.wikipedia.org/wiki/wake_on_lan#paquete_m%25c3%25a1gico][paquete m치gico]] que contiene 16 veces la [[https://es.wikipedia.org/wiki/direcci%25c3%25b3n_mac][mac]] del equipo a despertar. desde la lan no hay ning칰n problema: el paquete se env칤a a la direcci칩n de broadcast de la red, y el switch lo env칤a a todos los equipos.

desde internet es m치s complicado. se puede intentar abrir un puerto para wol, pero el router al intentar alcanzar al servidor en la ip interna lanzar치 un [[https://es.wikipedia.org/wiki/protocolo_de_resoluci%25c3%25b3n_de_direcciones][arp]] para conocer su direcci칩n mac y poder enviar el paquete. y si el ordenador est치 encendido no responder치, por lo que el paquete m치gico se quedar치 sin enviar.

la soluci칩n es modificar la tabla arp del router, dejando como permanente la direcci칩n ip y mac del servidor.

** nombre del servidor
la direcci칩n ip asignada a mi router por el isp es din치mica. para poder localizar mi servidor en internet es necesario tener un servicio de [[https://en.wikipedia.org/wiki/dynamic_dns][dynamic dns]]. he elegido a [[https://www.noip.com/][noip.com]] porque:
- tiene una cuenta gratuita
- mi router tiene el cliente necesario para actualizar la direcci칩n
- permite [[https://es.wikipedia.org/wiki/mx_(registro)][registros mx]] para el correo electr칩nico.

* servidor
en el ordenador he instalado los servicios e-mail y http.

** e-mail
utilizo [[https://www.exim.org/][exim4]] en una instalaci칩n estandar, con las siguientes configuraciones:
- el /hostname/ del ordenador es el mismo que el del dominio din치mico en noip.
- utilizo como [[https://wiki.debian.org/gmailandexim4][smarthost una direcci칩n de correo de gmail]]. el resultado es que puedo recibir correos en mi servidor, pero cuando los env칤o parecen todos enviados desde gmail.

a partir de aqu칤, ya puedo utilizar mi direcci칩n [[mailto:spam@alvarogonzalez.no-ip.biz][spam@alvarogonzalez.no-ip.biz]] para registrarme en cualquier sitio 游땙

** servidor web
el protocolo http es una buena forma de compartir ficheros. he instalado [[https://httpd.apache.org/][apache]] directamente desde el repositorio.


#+begin_example
apt install apache2 
#+end_example

para no dejar la p치gina por defecto, he instalado un mirror de este blog:

#+begin_example
 documentroot /var/www/alvarogonzalezsotillo.github.io
 <directory /var/www/alvarogonzalezsotillo.github.io>
          options followsymlinks
          allowoverride all
          require all granted
  </directory>
#+end_example

** owncloud
para acceder a mis ficheros (fundamentalmente fotograf칤as) utilizo owncloud, instalado desde repositorios:
#+begin_example
apt install mysql-server libapache2-mod-php php-mcrypt php-mysql
apt install owncloud-files
#+end_example

con esto se consigue un servidor apache capaz de ejecutar owncloud, pero la instalaci칩n de owncloud (en ~/var/www/owncloud~) no es accesible por apache. es necesario crear un fichero de sitio en ~/etc/apache/sites-available/owncloud.conf~ con el siguiente contenido

#+begin_example
  alias /owncloud /var/www/owncloud

  <directory /var/www/owncloud>
          options followsymlinks
          allowoverride all
          require all granted
  </directory>
#+end_example

despu칠s, se habilita el sitio con
#+begin_example
a2ensite owncloud
#+end_example

* configuraci칩n como /workstation/
el servidor tambi칠n deber칤a servirme de /backup/ en el caso de que no tenga disponible mi port치til. la siguiente configuraci칩n es la que utilizo para mi trabajo diario.

** zsh
zsh es una shell que puede sustituir a bash de forma casi transparente. las razones por las que utilizo zsh son
- mejor autocomplecci칩n con tabulador, tanto para ficheros como para opciones de comandos
- el historial de comandos se comparte entre todas las sesiones abiertas
- el historial de comandos se filtra por el comando parcial ya tecleado
- se puede utilizar ~**~ para hacer /globbing/ de directorios.
- los /plugins/ y temas de [[https://github.com/robbyrussell/oh-my-zsh][ohmyzsh]] /"will not make you a 10x developer...but you might feel like one"/. utilizo los plugis para =emacs=, =tmux=, =git= y =gradlew=, y el tema =robbyrussell=

** emacs
cuando tienes un martillo, todo te parecen clavos. [[https://www.gnu.org/software/emacs/][emacs]] es el martillo m치s grande que he usado nunca.

en un servidor, tiene la gran ventaja de que puede trabajarse directamente en una sesi칩n de ssh, sin entorno gr치fico. emacs y tmux son una combinaci칩n ganadora en estos casos.

en mi port치til he compilado emacs a partir de los fuentes, pero en el servidor bastar치 con utilizar un repositorio ppa:

   #+begin_src bash
   sudo add-apt-repository ppa:kelleyk/emacs
   sudo apt update
   sudo apt install emacs25 git
   #+end_src

la mejor parte de emacs es la configuraci칩n que cada usuario realiza con 칠l. la m칤a est치 en un repositorio git

   #+begin_src bash
   cd
   git clone https://alvarogonzalezsotillo@github.com/alvarogonzalezsotillo/.emacs.d.git
   #+end_src

al arrancar emacs, autom치ticamente descargar치 [[https://github.com/alvarogonzalezsotillo/.emacs.d/blob/master/my/my-packages.el][mis paquetes]] y activar치 mi configuraci칩n.

** materiales para clase
como cuento en [[../../../../blog/mi-publicacion-de-materiales-para-clase][otra entrada]], utilizo b치sicamente Latex y org-mode para mis clases.

La instalaci칩n de Latex, y los paquetes que utilizo, se consigue f치cilmente con:

  #+begin_src sh 
  sudo apt-get install texlive-collection-binextra \
  texlive-latex-recommended \
  texlive-extra-utils \
  texlive-collection-langspanish \
  texlive-collection-latex \
  texlive-collection-latexextra \
  #+end_src

Adem치s, utilizo otras herramientas como [[https://inkscape.org/en/][Inkscape]] y [[https://www.graphviz.org/][Graphviz]] que tambi칠n instalo con =apt-get=

** Ofim치tica
Aunque pr치cticamente ya no lo uso, de vez en cuando alguien de la familia necesita utiliza Microsoft Office. Para eso mantengo un prefijo de [[https://www.winehq.org/][Wine]] que copio de ordenador en ordenador, con la suite ofim치tica ya instalada.


