#+title: Literate Programming en la configuración de emacs

#+AUTHOR:      Álvaro González Sotillo
#+EMAIL:       alvarogonzalezsotillo@gmail.com
#+DATE:        2018-11-11
#+URI:         /blog/literate-programming-configuracion-emacs

#+TAGS: emacs, orgmode, 
#+DESCRIPTION: =org-babel= permite ejecutar los listados incluidos en un documento. Incluso la propia configuración de /emacs/ puede estar en un fichero =org=


#+PROPERTY: header-arg :eval query
#+LANGUAGE: es
#+options: toc:nil

Mi configuración de /emacs/ estaba basada en un fichero =init.el= con varios paquetes =elisp=. Gran parte de la configuración la extraía de ejemplos de otros ficheros =init.el=, y muchas veces olvidaba qué hacían algunas partes del fichero.

Esto se debía a una falta de comentarios, que se nos suele "olvidar" cuando sentimos que estamos programando, pero que solemos incluir cuando estamos redactando un documento. Descubrí en el blog de  [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua]] que podía mantener la configuración en un fichero =orgmode= y así documentar fácilmente cada opción.

* =init.el=

Emacs comienza cargando el fichero =~/.emacs.d/init.el=. Este fichero simplemente inicializa el sistema de paquetes y carga el paquete =org=, que es el que permite a Emacs manejar este tipo de ficheros. Después, carga este fichero interpretando los bloques de código.

#+begin_src lisp 
(package-initialize nil)
(setq package-check-signature nil)
(setq package-archives '(
      ("org" . "http://orgmode.org/elpa/")
      ("melpa" . "http://melpa.org/packages/")))


(package-initialize t)
(package-refresh-contents) ; OPCIONAL, NECESITA CONEXIÓN A INTERNET
(package-install 'org)
(require 'org)
(require 'ob-tangle)
(org-babel-load-file (expand-file-name "~/.emacs.d/config.org"))
#+end_src

Tras esto, =emacs= carga el fichero =config.org=, extrae los bloques de código y los ejecuta.

* Mi configuración
Se puede consultar mi configuración directamente en [[https://github.com/alvarogonzalezsotillo/.emacs.d/blob/master/config.org]]. Github es capaz de formatear el formato =org=, así que se ve bastante bonito.

También he generado una [[file:config-ejemplo.pdf][versión en pdf de la configuración, a fecha de esta entrada]] (pero es mejor mirar [[https://alvarogonzalezsotillo.github.io/.emacs.d/config.pdf][la última versión en PDF]] y en [[https://alvarogonzalezsotillo.github.io/.emacs.d/config.html][HTML]])

