# -*- coding: utf-8-unix; -*-
#+TITLE:       Blogueando con orgmode
#+AUTHOR:      츼lvaro Gonz치lez Sotillo
#+EMAIL:       alvarogonzalezsotillo@gmail.com
#+DATE:        2017-05-16 mar

# #+URI:         /blog/%y/%m/%d/%t/ Or /blog/%t/
# #+KEYWORDS:    keyword1, keyword2, keyword3
#+TAGS:        emacs, orgmode
#+DESCRIPTION: Es posible crear un blog sin (casi) salir de emacs.

#+LANGUAGE:    es
#+OPTIONS:     H:7 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t


*[[https://www.gnu.org/software/emacs/][Emacs]]* no es solo un editor de texto. Una vez que te decides a probarlo, no puedes parar de pensar en /qu칠 m치s puedo hacer sin salir de Emacs/. Este sitio web est치 hecho con [[http://orgmode.org/][*Orgmode*]], un /[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html][major mode]]/ de Emacs que permite generar documentos a partir de ficheros de texto plano (muy al estilo de [[https://en.wikipedia.org/wiki/Markdown][markdown]]).

Basados en Orgmode, existen [[http://orgmode.org/worg/org-blog-wiki.html][varios sistemas para generar un sitio web est치tico]], y despu칠s de probar algunos me he decidido por [[https://github.com/kelvinh/org-page][*org-page*]], aunque con un tema propio.



* Instalaci칩n de *org-page*
La forma m치s simple es utilizar el sistema de paquetes de *Emacs*. Basta con ejecutar =alt-x= =package-install org-page=

* Creaci칩n del sitio
Ejecutar =alt-x= =op/new-repository=. *Org-page* crear치 el directorio donde se almacenar치n los ficheros fuente del blog, e inicializar치 un repositorio *git*. Como se ver치 m치s adelante, *org-page* utiliza diferentes ramas para crear la publicaci칩n.

* Configuraci칩n de *org-page*
*Org-page* solo puede manejar un sitio a la vez. En mi caso, he creado un fichero de configuraci칩n en la ra칤z del sitio creado en el punto anterior, que ejecuto para generar el sitio.

#+CAPTION: [[https://github.com/alvarogonzalezsotillo/alvarogonzalezsotillo.github.io/blob/source/org-page-config.el][Fichero de configuraci칩n del sitio]]
#+begin_src lisp
(require 'org-page)
(setq op/repository-directory "/home/alvaro/github/alvarogonzalezsotillo.github.io")
(setq op/repository-org-branch "source")
(setq op/repository-html-branch "master")
(setq op/site-domain "https://alvarogonzalezsotillo.github.io/")
(setq op/personal-disqus-shortname "alvarogonzalezsotillo")
(setq op/hashover-comments nil)
(setq op/personal-github-link "https://github.com/alvarogonzalezsotillo")
(setq op/personal-avatar "/media/img/octaedron.png" )
(setq op/theme-root-directory "/home/alvaro/github/alvarogonzalezsotillo.github.io/themes/")
(setq op/theme 'alvaro)
(setq op/site-main-title "츼lvaro Gonz치lez Sotillo")
(setq op/site-sub-title "")

;; TRAS LA CONFIGURACI칍N, GENERO EL SITIO DE PRUEBA
(op/do-publication-and-preview-site op/site-preview-directory)
#+end_src

La mayor칤a de variables son autoexplicativas. Las variables relativas a la integraci칩n con *git* son:
- =op/repository-org-branch= : Indica la rama del repositorio donde se almancenan los ficheros fuentes del sitio. Aqu칤 residen los ficheros *org* y los ficheros de medios.
- =op/repository-html-branch= : Sobre esta rama se generar치 el sitio web. Los ficheros *org* se convertir치n a *html*, y se incluir치n los ficheros de medios.
- =op/theme-root-directory= : Fichero ra칤z con los temas del sitio
- =op/theme= : Subdirectorio dentro de =op/theme-root-directory= con el tema del sitio. En mi caso, he decidido modificar un tema incluido en *org-page*, por lo que lo incluyo tambi칠n en el repositorio *git*. Los ficheros del tema acaban incluidos en el sitio web, dentro del directorio =/media=.

* Publicaci칩n de una entrada
Una vez configurado, para crear una entrada puede ejecutarse =alt-x= =op/new-post=, que simplemente crea un nuevo fichero *org* en el subdirectorio =/blog=. La pr칩xima vez que se genere el sitio ser치 tenido en cuenta. Por ejemplo, este es el [[https://github.com/alvarogonzalezsotillo/alvarogonzalezsotillo.github.io/blob/source/blog/blogueando-con-orgmode/blogueando-con-orgmode.org][c칩digo fuente de esta entrada.]]

#+CAPTION: Ejemplo de fichero *org*
#+begin_src org

# -*- coding: utf-8-unix; -*-
#+TITLE:       Blogueando con orgmode
#+AUTHOR:      츼lvaro Gonz치lez Sotillo
#+EMAIL:       alvarogonzalezsotillo@gmail.com
#+DATE:        2017-05-16 mar

# #+URI:         /blog/%y/%m/%d/%t/ Or /blog/%t/
# #+KEYWORDS:    keyword1, keyword2, keyword3
#+TAGS:        emacs, orgmode
#+DESCRIPTION: Es posible crear un blog sin (casi) salir de emacs.

#+LANGUAGE:    es
#+OPTIONS:     H:7 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t


[[https://www.gnu.org/software/emacs/][Emacs]] no es solo un editor de texto. Una vez que te decides a probarlo, no puedes parar de pensar en /qu칠 m치s puedo hacer sin salir de Emacs/. Este sitio web est치 hecho con [[http://orgmode.org/][Orgmode]], un /[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html][major mode]]/ de Emacs que permite generar documentos a partir de ficheros de texto plano (muy al estilo de [[https://en.wikipedia.org/wiki/Markdown][markdown]]).

Basados en Orgmode, existen [[http://orgmode.org/worg/org-blog-wiki.html][varios sistemas para generar un sitio web est치tico]], y despu칠s de probar algunos me he decidido por [[https://github.com/kelvinh/org-page][org-page]], aunque con un tema propio.

[...]
#+end_src

* Resultado final
Este sitio est치 generado con *org-page*, como era de esperar 游땎. Utiliza la publicaci칩n de [[https://pages.github.com/][p치ginas est치ticas de *github*]] bas치ndose en el repositorio [[https://github.com/alvarogonzalezsotillo/alvarogonzalezsotillo.github.io][https://github.com/alvarogonzalezsotillo/alvarogonzalezsotillo.github.io]]


* 쯏 por qu칠 no usas *Wordpress*?

Trabajar con *emacs* y *git* ya es raz칩n suficiente, pero hay otras razones: posibilidad de trabajo /offline/ y el versionado de las p치ginas.

#+CAPTION: Comparaci칩n entre varios sistemas de publicaci칩n 
|                     | org-page                         | Google Sites                | Wordpress                                     |
|---------------------+----------------------------------+-----------------------------+-----------------------------------------------|
| /                   | <                                |                             |                                               |
| Hosting             | Cualquiera con p치ginas est치ticas | S칩lo Google                 | Cualquiera con p치ginas din치micas (PHP, MySql) |
| Trabajo /offline/   | *Si*                             | No                          | No                                            |
| Versionado          | *Git*                            | No                          | No                                            |
| Copias de seguridad | Repositorios Git                 | Google no se cae            | Posibles                                      |
| /Mirrors/           | Si                               | Google no necesita /mirror/ | Posible, pero laborioso                       |

